book_flow/urls.py
from django.urls import path, re_path, include
from django.views.generic import RedirectView

from book_flow import views
from book_flow.views import (BookListCreateView, BookDetailView, MostBorrowedBooksView, BookIssueCountView, \
                             TopLateReturnedBooksView, TopLateReturnUsersView, BookList, BookDetail, ReturnBookView,
                             IssueBookView, BookSearchView,
                             )

app_name = 'book_flow'

urlpatterns = [
    # Class-based views
    path('', BookList.as_view(), name='home'),
    path('books/', BookListCreateView.as_view(), name='get_books'),
    path('books/<int:book_id>/', BookDetailView.as_view(), name='get_book'),
    path('book_list', BookList.as_view(), name='book_list'),
    path('book_detail/<int:pk>/', BookDetail.as_view(), name='book_detail'),
    path('return-book/<int:book_id>/', ReturnBookView.as_view(), name='return_book'),
    path('issue-book/<int:book_id>/', IssueBookView.as_view(), name='issue_book'),

    path('search/', BookSearchView.as_view(), name='book_search'),
    path('add_to_favorites/<int:book_id>/', views.add_to_favorites, name='add_to_favorites'),
    path('remove_from_favorites/<int:book_id>/', views.remove_from_favorites, name='remove_from_favorites'),

    # API Endpoints
    path('most-borrowed-books/', MostBorrowedBooksView.as_view(), name='most-borrowed-books'),
    path('book-issue-count/', BookIssueCountView.as_view(), name='book-issue-count'),
    path('top-late-returned-books/', TopLateReturnedBooksView.as_view(), name='top-late-returned-books'),
    path('top-late-return-users/', TopLateReturnUsersView.as_view(), name='top-late-return-users'),

    path('book-statistics/', views.book_statistics_view, name='book-statistics')
]

final_lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('', lambda request: redirect('users:login')),
    path('books/', include('book_flow.urls', namespace='book_flow')),
    path('i18n/', include('django.conf.urls.i18n')),  # Add this line
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from django.views.generic import TemplateView

from book_flow.views import BookList
from users.views import (RegisterView, CustomLoginView, custom_logout_view,
                         ProfileView, OTPVerificationView, MyBookShelf, HomePageView)
app_name = 'users'

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', custom_logout_view, name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('my_shelf/', MyBookShelf.as_view(), name='my_shelf'),
    # OTP verification
    path('otp-verification/', OTPVerificationView.as_view(), name='otp_verification'),
    path('verification-success/', TemplateView.as_view(template_name="users/verification_success.html"),
         name='verification_success'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block base %}Base HTML{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/books/homepage.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/books/book_detail.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/books/book_list.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/books/book_search.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/books/book_issue.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/books/book_statistics.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/users/profile.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/users/my_shelf.css' %}">
    <!-- Swiper CSS and JS -->
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
</head>
<body>
    <div class="container">
        <!-- Sidebar -->
        <aside class="sidebar">
            <a href="{% url 'users:home' %}">
                <div class="logo">
                    My <span>Book</span> Shelf
                </div>
            </a>
            <nav>
                <ul class="nav-list">
                    <li><a href="{% url 'users:home' %}">Home</a></li>
                    <li><a href="{% url 'book_flow:book_search' %}">Search</a></li>
                    <li><a href="{% url 'users:my_shelf' %}">My Shelf</a></li>
                    <li><a href="{% url 'book_flow:book-statistics' %}">Stats</a></li>
                </ul>
            </nav>
            <footer class="footer-links">
                <a href="/about">About</a>
                <a href="/support">Support</a>
                <a href="/terms">Terms & Conditions</a>
            </footer>
        </aside>

        <!-- Main Content -->
        <div class="content-wrapper">
            <!-- Header -->
            <header class="header">
                <div class="search-bar">
                    <form method="GET" action="{% url 'book_flow:book_search' %}" class="search-form">
                        <input
                                type="text"
                                id="search-input"
                                name="query"
                                placeholder="Search by Title, Author, Keyword or ISBN"
                                aria-label="Search Books"
                                autocomplete="off"
                        >
                        <button type="submit">Search</button>
                    </form>
                    <div id="suggestions-container" class="suggestions">
                        <!-- Suggestions will appear here -->
                    </div>
                </div>
                <div class="header-controls">
                    <div class="datetime-container">
                        <div id="current-date">
                            <span class="calendar-icon">📅</span>
                            <span id="date-text"></span>
                        </div>
                        <div id="current-time">
                            <span class="clock-icon">⏰</span>
                            <span id="time-text"></span>
                        </div>
                    </div>
                    <nav>
                        {% if request.user.is_authenticated %}
                            <div class="dropdown">
                                <button class="dropdown-toggle" id="dropdownToggle" aria-expanded="false">
                                    {{ request.user.full_name }}
                                </button>
                                <div class="dropdown-menu" id="dropdownMenu" style="display: none;">
                                    <a href="{% url 'users:profile' %}">Profile</a>
                                    <a href="{% url 'users:my_shelf' %}">Favourites</a>
                                    <a href="{% url 'users:logout' %}">Log out</a>
                                </div>
                            </div>
                        {% else %}
                            <a href="{% url 'users:register' %}">Sign up</a>
                            <a href="{% url 'users:login' %}">Log in</a>
                        {% endif %}
                    </nav>
                </div>
            </header>

            <!-- Main Section -->
            <main class="main-content">
                {% block content %}
                <!-- Dynamic content will be rendered here -->
                {% endblock %}
            </main>
        </div>
    </div>



</body>
</html>